/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
	aws_project_region: 'eu-west-2',
	aws_cognito_identity_pool_id:
		'eu-west-2:c7cdccca-771d-45c8-b21a-25e1c4f84077',
	aws_cognito_region: 'eu-west-2',
	aws_user_pools_id: 'eu-west-2_oFxylY231',
	aws_user_pools_web_client_id: '2qf1igfh1mfd03h2vpk8605gsb',
	oauth: {},
	aws_appsync_graphqlEndpoint:
		'https://35uvaqx7nvbnjpmygxu2pl2jym.appsync-api.eu-west-2.amazonaws.com/graphql',
	aws_appsync_region: 'eu-west-2',
	aws_appsync_authenticationType: 'AMAZON_COGNITO_USER_POOLS',
	aws_appsync_apiKey: 'da2-3nt75kuzazct3owx33wqudnaby',
	aws_user_files_s3_bucket:
		'wbsampleplatform2758cd1e82254591bb63b643a95dc131856-dev',
	aws_user_files_s3_bucket_region: 'eu-west-2',
	aws_content_delivery_bucket:
		'wbsamplelatform-20210502172948-hostingbucket-dev',
	aws_content_delivery_bucket_region: 'eu-west-2',
	aws_content_delivery_url:
		'http://wbsamplelatform-20210502172948-hostingbucket-dev.s3-website.eu-west-2.amazonaws.com',
};

export default awsmobile;
